version: "3"

services:
    dev:
        build: .
        volumes:
         - ".:/home"
        ports:
         - 8000:8000 
    
    start_server:
        build: .
        command: python3 PickEat/manage.py runserver 0.0.0.0:8000
        volumes:
         - ".:/home"
        ports:
         - "8000:8000"

    run_unit_tests:
        build: .
        command: python3 PickEat/manage.py test
        volumes:
         - ".:/home"
        ports:
         - "8000:8000"
